---
title: Personas for DaSL Products
toc: false
---

Personas are fictionalized representations of different roles around FHCC. They depict the key tasks and challenges that FHCC staff perform, as well as hopes for how things could be improved in a future state. Personas help anchor product design to user needs.

The HCI group is creating personas to describe common data problems at Fred Hutch. This work continues the needs assessment done in 2023.

# How are we doing this work?

We are conducting ongoing research using a mix of qualitative and quantitative methods to understand user needs, including interviews, usage analytics, and evaluative methods.

# Help us understand your data infrastructure needs

Although personas are primarily internal documentation of user needs, we are making ours public so that YOU can help us improve our understanding of data infrastructure and tooling needs around Fred Hutch.

**Our personas are a work in progress** and do not represent everything we have learned. However, **we would love to hear from you** no matter what. If you see a missing problem area, a factual inaccuracy, a role that you think is not captured that should be -- email us at `data@fredhutch.org` or fill out [this form](https://forms.office.com/r/4Nh20Zk8NB).

A big thank you to members of the FHCC community who have already helped us develop these personas, including members of the clinical analytics and financial analytics teams, DaSL team members who collaborated closely in creating them, and other helpful individuals!

# Current personas by problem area

We group our personas by general problem area below.

## Running research data analyses on the cloud

-   [Larry the Learner](/family/proof/larry-the-learner.html)
-   [Preeti the PI](/family/proof/preeti-the-pi.html)
-   [Daesung the data scientist](/family/proof/daesung-the-data-scientist.html)
-   [Bisei the bioinformatician](/family/proof/bisei-the-bioinformatics-researcher.html)

## Working with patient data

-   [Bobby the biostatistician](/family/cards/bobby-the-biostatistician.html)
-   [Carina the clinical researcher](/family/cards/carina-the-clinical-researcher.html)
-   [DJ the data governance analyst](/family/cards/DJ-data-governance-analyst.html)
-   [Tammy the data scientist](/family/cards/Tammy-the-data-scientist.html)
-   [Alex the BI/analytics engineer](/family/cards/Alex-the-bi-analytics-engineer.html)
-   [Fundikira the financial analyst](/family/cards/Fundikira-the-financial-analyst.html)
-   [Bashir the business analyst](/family/cards/Bashir-the-business-analyst.html)
-   [Melissa the clinical analyst](/family/cards/melissa-clinical-analyst.html)
